name: Deploy to Production
on:
  workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "~/scripts/0_pull_repo.sh"
      